In [1]:
import numpy as np

In [2]:
# Numpy arrays

In [ ]:
# Creating ndarrays

In [111]:
arr1D = np.array([1.1, 2.2, 3.3, 4.4, 5.5]); arr1D

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [4]:
type(arr1D)

numpy.ndarray

In [5]:
arr2D = np.array([[1, 2], [3, 4]]); arr2D

array([[1, 2],
       [3, 4]])

In [6]:
arr4D = np.array(range(16)).reshape((2, 2, 2, 2)); arr4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
# shape and dtype

In [8]:
arr1D.shape

(5,)

In [9]:
arr2D.shape

(2, 2)

In [10]:
arr4D.shape

(2, 2, 2, 2)

In [11]:
arr4D.dtype

dtype('int64')

In [12]:
arr1D.dtype

dtype('float64')

In [13]:
# numpy methods to create ndarrays

In [14]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.random.randn(2,2)

array([[ 0.57370365, -1.22229931],
       [-1.25539335,  1.11372387]])

In [19]:
# Datatypes

In [20]:
np.array([-1, 0, 1], dtype=np.float128)

array([-1.,  0.,  1.], dtype=float128)

In [21]:
np.array([-1, 0, 1], dtype=np.bool)

array([ True, False,  True])

In [22]:
arr1D.dtype

dtype('float64')

In [23]:
arr1D.astype(np.int64).dtype

dtype('int64')

In [114]:
arr1D.astype(np.int64)

array([1, 2, 3, 4, 5])

In [24]:
# ndarray operations

In [25]:
arr2D

array([[1, 2],
       [3, 4]])

In [26]:
arr2D * 4

array([[ 4,  8],
       [12, 16]])

In [27]:
2*arr2D + 3*arr2D

array([[ 5, 10],
       [15, 20]])

In [28]:
arr2D ** 2

array([[ 1,  4],
       [ 9, 16]])

In [29]:
arr2D + 10

array([[11, 12],
       [13, 14]])

In [30]:
arr2D.transpose()

array([[1, 3],
       [2, 4]])

In [31]:
arr2D.reshape((4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [32]:
arr = np.random.randn(9).reshape((3,3)); arr

array([[ 0.64296696, -1.35386668, -0.63063743],
       [ 0.95263566, -0.93655218,  0.95181922],
       [-0.19093967, -0.93260398, -1.58520989]])

In [33]:
np.min(arr)

-1.5852098934609051

In [34]:
np.abs(arr)

array([[0.64296696, 1.35386668, 0.63063743],
       [0.95263566, 0.93655218, 0.95181922],
       [0.19093967, 0.93260398, 1.58520989]])

In [35]:
arr[1, :] = np.nan; arr

array([[ 0.64296696, -1.35386668, -0.63063743],
       [        nan,         nan,         nan],
       [-0.19093967, -0.93260398, -1.58520989]])

In [36]:
np.isnan(arr)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [37]:
arr1 = np.random.randn(9).reshape((3,3)); arr1

array([[ 0.32102068, -0.51877544, -1.28267292],
       [-1.34842617,  0.61170993, -0.5561239 ],
       [ 1.41138027, -2.4951374 ,  1.30766648]])

In [38]:
arr2 = np.random.randn(9).reshape((3,3)); arr2

array([[ 0.33189432,  0.82416396, -0.17453351],
       [-1.59689203, -0.42352094,  0.22643589],
       [-1.80766151,  0.26201455, -0.08469759]])

In [39]:
np.greater(arr1, arr2)

array([[False, False, False],
       [ True,  True, False],
       [ True, False,  True]])

In [40]:
arr1 > arr2

array([[False, False, False],
       [ True,  True, False],
       [ True, False,  True]])

In [41]:
# Indexing and slicing in Numpy arrays

In [42]:
# Basic indexing

In [43]:
arr = np.random.randn(3,3); arr

array([[-0.04113926, -0.273338  , -1.05294723],
       [ 1.65004669, -0.09589629,  0.15586867],
       [ 0.39533427,  1.47193681,  0.32148741]])

In [44]:
arr[0]

array([-0.04113926, -0.273338  , -1.05294723])

In [45]:
arr[0][1]

-0.2733379996693689

In [46]:
arr[0, 1]

-0.2733379996693689

In [47]:
arr[-1]

array([0.39533427, 1.47193681, 0.32148741])

In [48]:
# Slicing

In [49]:
arr[1:]

array([[ 1.65004669, -0.09589629,  0.15586867],
       [ 0.39533427,  1.47193681,  0.32148741]])

In [50]:
arr[1:, :2]

array([[ 1.65004669, -0.09589629],
       [ 0.39533427,  1.47193681]])

In [51]:
arr[1:2, -2:-1]

array([[-0.09589629]])

In [52]:
arr[:][2]

array([0.39533427, 1.47193681, 0.32148741])

In [53]:
arr[:][:]

array([[-0.04113926, -0.273338  , -1.05294723],
       [ 1.65004669, -0.09589629,  0.15586867],
       [ 0.39533427,  1.47193681,  0.32148741]])

In [54]:
arr1 = arr[1:2]; arr1

array([[ 1.65004669, -0.09589629,  0.15586867]])

In [55]:
arr1[:] = 0; arr1

array([[0., 0., 0.]])

In [56]:
arr

array([[-0.04113926, -0.273338  , -1.05294723],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.39533427,  1.47193681,  0.32148741]])

In [57]:
arr_copy = arr.copy()

In [58]:
arr_copy[1:2] = 1; arr_copy

array([[-0.04113926, -0.273338  , -1.05294723],
       [ 1.        ,  1.        ,  1.        ],
       [ 0.39533427,  1.47193681,  0.32148741]])

In [59]:
arr

array([[-0.04113926, -0.273338  , -1.05294723],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.39533427,  1.47193681,  0.32148741]])

In [60]:
arr[:] = np.nan; arr

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [61]:
# Boolean/conditional indexing

In [62]:
arr = np.random.randn(3,3); arr

array([[-0.50566069, -0.52115534,  0.0757591 ],
       [ 1.67500165, -0.99280199,  0.80878346],
       [ 0.56937775,  0.36614928, -0.02532004]])

In [63]:
arr < 0

array([[ True,  True, False],
       [False,  True, False],
       [False, False,  True]])

In [64]:
arr[(arr < 0)]

array([-0.50566069, -0.52115534, -0.99280199, -0.02532004])

In [65]:
(arr > -1) & (arr < 1)

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [66]:
arr[((arr > -1) & (arr < 1))]

array([-0.50566069, -0.52115534,  0.0757591 , -0.99280199,  0.80878346,
        0.56937775,  0.36614928, -0.02532004])

In [67]:
arr[(arr < -1) | (arr > 1)]

array([1.67500165])

In [68]:
# Indexing with arrays

In [69]:
arr

array([[-0.50566069, -0.52115534,  0.0757591 ],
       [ 1.67500165, -0.99280199,  0.80878346],
       [ 0.56937775,  0.36614928, -0.02532004]])

In [70]:
arr[[0, 2]]

array([[-0.50566069, -0.52115534,  0.0757591 ],
       [ 0.56937775,  0.36614928, -0.02532004]])

In [71]:
arr[[0, 2], [1]]

array([-0.52115534,  0.36614928])

In [72]:
arr[[2, 0]]

array([[ 0.56937775,  0.36614928, -0.02532004],
       [-0.50566069, -0.52115534,  0.0757591 ]])

In [73]:
# Vectorized computation and data processing

In [74]:
# Mathematical operations

In [75]:
arr

array([[-0.50566069, -0.52115534,  0.0757591 ],
       [ 1.67500165, -0.99280199,  0.80878346],
       [ 0.56937775,  0.36614928, -0.02532004]])

In [76]:
np.mean(arr)

0.16112590941903046

In [77]:
np.mean(arr, axis=0)

array([ 0.5795729 , -0.38260268,  0.28640751])

In [78]:
np.mean(arr, axis=1)

array([-0.31701898,  0.49699438,  0.30340233])

In [79]:
np.argmax(arr)

3

In [80]:
np.argmax(arr, axis=1)

array([2, 0, 0])

In [81]:
np.cumsum(arr)

array([-0.50566069, -1.02681603, -0.95105693,  0.72394472, -0.26885726,
        0.5399262 ,  1.10930395,  1.47545322,  1.45013318])

In [82]:
np.cumsum(arr, axis=1)

array([[-0.50566069, -1.02681603, -0.95105693],
       [ 1.67500165,  0.68219967,  1.49098313],
       [ 0.56937775,  0.93552702,  0.91020698]])

In [83]:
# Boolean operations

In [84]:
arr_bool = (arr > -0.5) & (arr < 0.5); arr_bool

array([[False, False,  True],
       [False, False, False],
       [False,  True,  True]])

In [85]:
arr_bool.any()

True

In [86]:
arr_bool.any(axis=1)

array([ True, False,  True])

In [87]:
arr_bool.all()

False

In [88]:
arr_bool.all(axis=1)

array([False, False, False])

In [89]:
# Sorting

In [90]:
arr1D = np.random.randn(10); arr1D

array([ 1.14322028,  1.61792721, -1.01446969,  1.26988026, -0.20110113,
       -0.28283051,  0.73009565, -0.68766388,  0.27276319, -0.7135162 ])

In [91]:
np.sort(arr1D)

array([-1.01446969, -0.7135162 , -0.68766388, -0.28283051, -0.20110113,
        0.27276319,  0.73009565,  1.14322028,  1.26988026,  1.61792721])

In [92]:
arr1D

array([ 1.14322028,  1.61792721, -1.01446969,  1.26988026, -0.20110113,
       -0.28283051,  0.73009565, -0.68766388,  0.27276319, -0.7135162 ])

In [93]:
np.argsort(arr1D)

array([2, 9, 7, 5, 4, 8, 6, 0, 3, 1])

In [94]:
arr1D.sort()
np.argsort(arr1D)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
# Searching

In [96]:
arr1 = np.array(range(1, 11)); arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr2 = arr1 * 1000; arr2

array([ 1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,  9000,
       10000])

In [112]:
cond = np.random.randn(10) > 0; cond

array([False,  True,  True,  True, False, False,  True,  True, False,
        True])

In [99]:
np.where(cond, arr1, arr2)

array([1000, 2000,    3, 4000, 5000,    6,    7,    8, 9000,   10])

In [100]:
# File operations and Numpy arrays

In [101]:
# Text files

In [102]:
arr

array([[-0.50566069, -0.52115534,  0.0757591 ],
       [ 1.67500165, -0.99280199,  0.80878346],
       [ 0.56937775,  0.36614928, -0.02532004]])

In [103]:
np.savetxt('arr.csv', arr, fmt='%0.2lf', delimiter=',')

In [104]:
!cat arr.csv

-0.51,-0.52,0.08
1.68,-0.99,0.81
0.57,0.37,-0.03


In [105]:
arr_new = np.loadtxt('arr.csv', delimiter=','); arr_new

array([[-0.51, -0.52,  0.08],
       [ 1.68, -0.99,  0.81],
       [ 0.57,  0.37, -0.03]])

In [106]:
# Binary files

In [107]:
np.save('arr', arr)

In [108]:
!cat arr.npy

�NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (3, 3), }                                                          
z�NR_.��M�࿯����d�?�����?�����p܍��?cï�W8�?�#b�n�?)?홿

In [109]:
arr_new = np.load('arr.npy'); arr_new

array([[-0.50566069, -0.52115534,  0.0757591 ],
       [ 1.67500165, -0.99280199,  0.80878346],
       [ 0.56937775,  0.36614928, -0.02532004]])

In [110]:
arr == arr_new

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])